---
- name: Load OS specific values
  include_vars: "{{ ansible_os_family }}.yml"

- include: add_groups.yml

- include: users.yml

- include: remove_groups.yml

- include: ssh_keys.yml

- include: sudo.yml
